from resumake.components import *

# TODO: edit author object as required
author = Author(
    name="Sheikh Saad Abdullah",
    address=Address("2060 Quingate Place", "B3L 4P7"),
    phone="+1 (902) 818-0048",
    email="sheikh@cybar.dev",
    website="www.cybar.dev",
    social="cybardev",
    skills=[
        Skill(
            name="Skills",
            attributes=[
                "Python",
                "HTML",
                "CSS",
                "Bootstrap",
                "JavaScript",
                "jQuery",
                "ReactJS",
                "NodeJS",
                "ExpressJS",
                "MongoDB",
                "Java",
                "C/C++",
                "Git",
            ],
        ),
        Skill(
            name="Interests",
            attributes=[
                "Linux",
                "Open-source",
                "Shell Scripting",
                "Automation",
                "Cloud",
                "CI/CD",
                "DevOps",
                "Agile Development",
                "Data Analytics",
            ],
        ),
    ],
    experiences=[
        Experience(
            name="ReelData AI",
            address="Halifax, Nova Scotia",
            role="Junior Software Developer",
            start="Sept 2023",
            end="Dec 2023",
            attributes=[
                "Collaborated with a dynamic Agile team on ReelAppetite, a key product, demonstrating strong teamwork and interpersonal skills",
                "Successfully integrated into a large existing codebase, showcasing adaptability and quick learning",
                "Implemented features using test-driven development and containerization, contributing to the software's robustness",
                "Experienced the deployment of code to production, highlighting practical application and impact of contributions",
            ],
        ),
        Experience(
            name="Sensor Technology LTD (COVE)",
            address="Dartmouth, Nova Scotia",
            role="Research Intern",
            start="May 2023",
            end="Aug 2023",
            attributes=[
                "Configured Raspberry Pi SBCs with OpenPlotter Marine OS for the purpose of developing and testing the Acoustic Projector Control and Logging System",
                "Developed Python script for generation and playback of audio files from given wavelength and duration",
                "Implemented module to connect to private Signal K server and utilize its API to effectively retrieve sensor data",
                "Created a script for logging data from sensors, consuming it via API calls, and storing it in an SQLite database",
            ],
        ),
    ],
    projects=[
        Project(
            name="Resumake - Programmatic Resume Generator",
            address="https://github.com/cybardev/resumake",
            role="Software Developer",
            start="Jun 2022",
            end="Present",
            attributes=[
                "Modularized code by splitting up project into multiple component files and using proper object-oriented techniques to ensure separation of concerns",
                "Containerized application in a Docker image via Dockerfile configuration to create self-contained package with proper dependency resolution",
                "Packaged and published project to Python Package Index (PyPI), DockerHub, and GitHub Packages registries, making it easy and convenient for users to install",
                "Created GitHub Actions workflows for CI/CD, to automatically build and deploy to package registries on tagged pushes, as well as re-generating personal resume and publishing to static website (https://resume.cybar.dev)",
            ],
        ),
        Project(
            name="Accessible Blog with CMS",
            address="https://github.com/SMU-Code-C/blog",
            role="Full-stack Developer",
            start="Jan 2022",
            end="Apr 2022",
            attributes=[
                "Built a 3-page blog website as well as a custom CMS (content management system) admin page",
                "Created an accessible on-screen keyboard to accommodate client's typing difficulties caused by Cerebral Palsy",
                "Implemented the blog as a full-stack webapp using Bootstrap, jQuery, AlpineJS, Node, Express, and MongoDB",
                "Enforced CRUD standards to effectively exchange blog post contents to and from NoSQL database",
            ],
        ),
    ],
    education=Education(
        school="Saint Mary's University",
        location="Halifax, Nova Scotia",
        program="Bachelor of Science",
        major="Computing Science",
        start="Sep 2020",
        end="Dec 2024",
        courses=[
            "Artificial Intelligence",
            "Data Structures and Algorithms",
            "Software Engineering",
            "Systems Security",
        ],
    ),
)
