name: Build and Publish Pipeline

on:
  push:
    tags: "v*"

jobs:
  update-resume:
    name: Update Resume
    if: github.repository == 'cybardev/resumake'
    uses: ./.github/workflows/update-resume.yml
