name: Build and Release Binaries

on:
  # run on tagged push
  push:
    tags: "v*"

  # Allows running this workflow from other workflows
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"

      - name: Build for ${{ matrix.os }} (${{ matrix.arch }})
        id: builds
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          [ "$GOOS" = "windows" ] && EXT=".exe" || EXT=""
          go build -o "bin/${GOOS}-${GOARCH}/resumake${EXT}"

      - name: Create Release Archives
        run: |
          [ "${{ matrix.os }}" = "windows" ] && EXT=".exe" || EXT=""
          cd "bin/${{ matrix.os }}-${{ matrix.arch }}"
          zip "../resumake-${{ matrix.os }}-${{ matrix.arch }}.zip" "resumake${EXT}" "../../resources/*" "../../static/*"

      - name: Create Release with pushed tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            bin/*.zip
