name: Build and Release Binaries

on:
  # run on tagged push
  push:
    tags: "v*"

  # Allows running this workflow from other workflows
  workflow_call:

# Sets permissions of the GITHUB_TOKEN to allow releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"

      - name: Run Linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.6
          args: --disable=errcheck

      - name: Create Release Archives
        run: |
          ARCH_LIST=("amd64" "arm64")
          OS_LIST=("linux" "darwin" "windows")

          for GOARCH in "${ARCH_LIST[@]}"; do
              for GOOS in "${OS_LIST[@]}"; do
                  [ "${GOOS}" == "windows" ] && EXT=".exe" || EXT=""
                  echo "Building for ${GOOS}-${GOARCH}..."
                  go build -o "bin/${GOOS}-${GOARCH}/resumake${EXT}"
                  echo "Build complete. Creating archives..."
                  (cd bin/${GOOS}-${GOARCH} && zip ../resumake-${GOOS}-${GOARCH}.zip resumake${EXT} ../../resources/* ../../static/site/*)
                  echo "Archives generated. Cleaning up build files..."
                  rm -rf "bin/${GOOS}-${GOARCH}/"
                  echo "DONE."
                  echo
              done
          done

      - name: Create Release with pushed tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            bin/*.zip
