name: Build and Release Binaries

on:
  # run on tagged push
  push:
    tags: "v*"

  # Allows running this workflow from other workflows
  workflow_call:

# Sets permissions of the GITHUB_TOKEN to allow releases
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.2"

      - name: Run Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61

      - name: Build for ${{ matrix.os }} (${{ matrix.arch }})
        id: builds
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          [ "$GOOS" = "windows" ] && EXT=".exe" || EXT=""
          go build -o "bin/${GOOS}-${GOARCH}/resumake${EXT}"

      - name: Create Release Archive for ${{ matrix.os }} (${{ matrix.arch }})
        run: |
          [ "${{ matrix.os }}" = "windows" ] && EXT=".exe" || EXT=""
          cd "bin/${{ matrix.os }}-${{ matrix.arch }}"
          zip "../resumake-${{ matrix.os }}-${{ matrix.arch }}.zip" "resumake${EXT}" "../../resources/*" "../../static/*"

      - name: Upload ${{ matrix.os }}-${{ matrix.arch }} archive
        uses: actions/upload-artifact@v2
        with:
          name: resumake-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            bin/resumake-${{ matrix.os }}-${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Release Archives
        uses: actions/download-artifact@v2
        with:
          path: |
            bin/

      - name: Create Release with pushed tag
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            bin/*/*.zip
