name: "[TEST] Resume Builder"

on:
  # Allows running this workflow from GitHub Actions tab
  workflow_dispatch:

# configuration variables
env:
  AUTHOR_NAME: Sheikh Saad Abdullah
  RESUME_FILE: resume.yml
  RESUME_MARGIN: 6

jobs:
  generate-resume:
    name: Generate Resume
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: pandoc wkhtmltopdf poppler-utils fonts-roboto
          version: 1.0

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run resume generation script
        id: resumake
        run: |
          # --< variables >-- #
          AUTHOR="$(echo ${{ env.AUTHOR_NAME }} | tr ' ' '_')"
          TEMPFILE="./_resume.md"
          OUTFILE="./static/assets/Resume_${AUTHOR}.pdf"

          # --< create metadata file with resume info >-- #
          echo "---" >${TEMPFILE}
          cat ${{ env.RESUME_FILE }} >>${TEMPFILE}
          echo "---" >>${TEMPFILE}

          # --< generate resume PDF >-- #
          pandoc -s "${TEMPFILE}" -t html \
            --template=resources/template.html \
            --metadata=title:Resume_${AUTHOR} --variable papersize=letter \
            --variable margin-top=${{ env.RESUME_MARGIN }} --variable margin-right=0 \
            --variable margin-bottom=0 --variable margin-left=0 \
            --pdf-engine=wkhtmltopdf --pdf-engine-opt=--enable-local-file-access \
            -o "${OUTFILE}"

          echo "author=${AUTHOR}" >> "${GITHUB_OUTPUT}"
      - name: Generate PNG preview
        run: |
          AUTHOR="${{ steps.resumake.outputs.author }}"
          pdftoppm -png "./static/assets/Resume_${AUTHOR}.pdf" > "./static/assets/Resume_${AUTHOR}.png"
      - name: Upload resume files
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: static/assets/Resume_*.p*
