name: Resume Builder

on:
    # Allows running this workflow from other workflows
    workflow_call:
        outputs:
            description: tells downstream jobs if they should be skipped
            value: ${{ jobs.generate-resume.outputs.skip }} == 'true' || ${{ jobs.generate-resume.outputs.changed }} == 'false'

jobs:
    generate-resume:
        name: Generate Resume
        runs-on: ubuntu-latest
        outputs:
            changed: ${{ steps.check_updates.outputs.changed }}
            skip: ${{ steps.generate.outputs.skip }}
        steps:
            - name: Install dependencies
              uses: awalsh128/cache-apt-pkgs-action@latest
              with:
                  packages: pandoc wkhtmltopdf poppler-utils
                  version: 1.0

            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Run resume generation script
              id: generate
              run: |
                  RESUME_SCRIPT="./resume/${{ github.repository_owner }}.py"
                  if [[ -f "${RESUME_SCRIPT}" ]]; then
                      export PYTHONPATH=$PYTHONPATH:$PWD/src/
                      python3 -m resumake.builder ${RESUME_SCRIPT} -o ./static/assets
                      FILENAME=$(basename $(ls ./static/assets/Resume_*.pdf) .pdf)
                      echo | pandoc -t html --template=./src/resumake/template/index.html --metadata title="${FILENAME}" --variable filename="${FILENAME}" -o ./static/index.html
                      echo "skip=false" >> "${GITHUB_OUTPUT}"
                  else
                      echo "File '${RESUME_SCRIPT}' not found. Couldn't build resume."
                      echo "skip=true" >> "${GITHUB_OUTPUT}"
                  fi
            - name: Check for resume changes
              id: check_updates
              if: steps.generate.outputs.skip == 'false'
              run: |
                  RESUME_CHANGED=$(git diff ./static/assets | grep md | head -n 1)
                  INDEX_CHANGED=$(git diff ./static | grep index.html | head -n 1)
                  UPDATE=$(python3 -c "print(str('${RESUME_CHANGED}'.endswith('.md') or '${INDEX_CHANGED}'.endswith('html')).lower())")
                  echo "Re-upload resume: ${UPDATE}"
                  echo "changed=${UPDATE}" >> "${GITHUB_OUTPUT}"
            - name: Commit changes
              if: steps.generate.outputs.skip == 'false' && steps.check_updates.outputs.changed == 'true'
              run: |
                  git config --local user.name "github-actions[bot]"
                  git config --local user.email "github-actions[bot]@users.noreply.github.com"
                  git commit -a -m "pipeline: update resume"
            - name: Upload resume files
              if: steps.generate.outputs.skip == 'false' && steps.check_updates.outputs.changed == 'true'
              uses: ad-m/github-push-action@master
              with:
                  branch: main
                  github_token: ${{ secrets.GITHUB_TOKEN }}
