name: "[TEST] Resume Builder"

on:
  # Allows running this workflow from GitHub Actions tab
  workflow_dispatch:

# configuration variables
env:
  AUTHOR_NAME: Sheikh Saad Abdullah
  RESUME_FILE: resume.yml
  RESUME_MARGIN: 6

jobs:
  generate-resume:
    name: Generate Resume
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: poppler-utils
          version: 1.0
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run resume generator
        id: resumake
        run: |
          AUTHOR="$(echo ${{ env.AUTHOR_NAME }} | tr ' ' '_')"
          curl -X POST -F "resume=@${{ env.RESUME_FILE }}" "https://resumake.cybar.dev/resume/" > "./static/assets/Resume_${AUTHOR}.pdf"
          echo "author=${AUTHOR}" >> "${GITHUB_OUTPUT}"
      - name: Generate PNG preview
        continue-on-error: true
        run: |
          AUTHOR="${{ steps.resumake.outputs.author }}"
          pdftoppm -png "./static/assets/Resume_${AUTHOR}.pdf" > "./static/assets/Resume_${AUTHOR}.png"
      - name: Upload resume files
        uses: actions/upload-artifact@v4
        with:
          name: resume
          path: static/assets/Resume_*.p*
