name: Create New Tag on Version Change

on:
    push:
        branches: main
        paths: pyproject.toml

jobs:
    generate-resume:
        runs-on: ubuntu-latest
        if: "${{ startsWith(github.event.head_commit.message, 'update: new version') }}"
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Create Tag
              run: |
                  VERSION_STRING=$(cat pyproject.toml | grep 'version')
                  TAG=$(python3 -c "print('v' + '${VERSION_STRING}'.split('=')[1].strip().strip('\"'))")
                  git tag ${TAG} main
                  git push origin ${TAG}
