name: Update Resume

on:
    # TODO: uncomment the following 3 lines on forks
    # push:
    #     branches: main
    #     paths: "resume/*.py"

    # Allows running this workflow from other workflows
    workflow_call:

    # Allows running this workflow from GitHub Actions tab
    workflow_dispatch:

jobs:
    generate-resume:
        name: Generate Resume
        uses: ./.github/workflows/resume.yml

    publish-site:
        name: Publish Site
        needs: generate-resume
        if: needs.generate-resume.outputs.skip == 'false'
        uses: ./.github/workflows/website.yml
